name: sy_customs
description: "A Flutter package that contains custom widgets."
version: 0.1.18
homepage: https://github.com/sydeveloperslk/sy_customs
repository: "https://github.com/sydeveloperslk/sy_customs"
 
environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  gap: ^3.0.1
  swipeable_button_view: ^0.0.2
  shared_preferences: ^2.3.2
  intl: ^0.20.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/svg/
    
  # plugin:
  #   platforms:
  #     ios:
  #       pluginClass: sy_customs
  #     windows:
  #       pluginClass: sy_customs

 
   
