name: sy_customs
description: "A Flutter package that contains custom widgets."
version: 0.0.5
homepage: https://github.com/sydeveloperslk/sy_customs
repository: "https://github.com/sydeveloperslk/sy_customs"
 
environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
 
   
